---
- name: A Playbook to test Async and Poll
  hosts: web
  tasks:
    - name: Copy the script 
      copy: 
        src: "longrunningscript.sh" # the file is present on the same directory
        dest: "/tmp"
    
    - name: Execute the script
      shell:
        "chmod a+x /tmp/longrunningscript.sh &&  /tmp/longrunningscript.sh 60" # Run for 60 seconds 
      async: 18 # Maximum allowed time in Seconds
      poll: 2 # Polling Interval in Seconds
      register: scrout

    - name: Execute the script second
      shell:
        "chmod a+x /tmp/longrunningscript.sh &&  /tmp/longrunningscript.sh 60" # Run for 60 seconds
      async: 18 # Maximum allowed time in Seconds
      poll: 3 # Polling Interval in Seconds
      register: scrout1


