- name: nginx
  hosts: all
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present
    - name: copy nginx config file
      copy: src=./config/default dest=/etc/nginx/sites-available/
      notify:
        - Start nginx
  handlers:
    - name: Start nginx
      service:
        name: nginx
        state: started

