- name: Enable Intranet Services
  hosts: web
  become: yes
  tasks:
    - name: Install httpd and firewalld
      apt:
        name: 
          - apache2
          - firewalld
        state: latest
      notify: 
        - restart httpd

    - name: Enable and Run Firewalld
      service: 
        name: firewalld
        enabled: true
        state: started
    - name: firewalld permitt httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Test html page is installed
      copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: apache2
        enabled: true
        state: restarted

- name: Test intranet web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to intranet webserver
      uri: 
        url: http://3.110.44.31
        status_code: 200
